// <auto-generated />
using System;
using ApiPasteles.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPasteles.Migrations
{
    [DbContext(typeof(PastelesContext))]
    partial class PastelesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiPasteles.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Pastel")
                        .HasColumnType("int");

                    b.Property<double?>("Presentacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("float");

                    b.Property<double?>("Sabor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("float")
                        .HasColumnName("sabor");

                    b.Property<int?>("Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Califica__3213E83FC1F99D51");

                    b.HasIndex("Pastel");

                    b.HasIndex("Usuario");

                    b.ToTable("Calificacion", (string)null);
                });

            modelBuilder.Entity("ApiPasteles.Models.Pastel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Origen")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Precio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK__Pastel__3213E83F446B6C09");

                    b.ToTable("Pastel", (string)null);
                });

            modelBuilder.Entity("ApiPasteles.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3213E83F34DEF25A");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ApiPasteles.Models.Calificacion", b =>
                {
                    b.HasOne("ApiPasteles.Models.Pastel", "PastelNavigation")
                        .WithMany("Calificacions")
                        .HasForeignKey("Pastel")
                        .HasConstraintName("FK__Calificac__Paste__5FB337D6");

                    b.HasOne("ApiPasteles.Models.Usuario", "UsuarioNavigation")
                        .WithMany("Calificacions")
                        .HasForeignKey("Usuario")
                        .HasConstraintName("FK__Calificac__Usuar__5EBF139D");

                    b.Navigation("PastelNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("ApiPasteles.Models.Pastel", b =>
                {
                    b.Navigation("Calificacions");
                });

            modelBuilder.Entity("ApiPasteles.Models.Usuario", b =>
                {
                    b.Navigation("Calificacions");
                });
#pragma warning restore 612, 618
        }
    }
}
